// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_8gUM_qGpv8-RMLBhq8GGi_uR1v7kHcw',
    appId: '1:716831834046:web:bfa5f51a16d2e6fc2f83ef',
    messagingSenderId: '716831834046',
    projectId: 'app-segurity-64cb8',
    authDomain: 'app-segurity-64cb8.firebaseapp.com',
    storageBucket: 'app-segurity-64cb8.firebasestorage.app',
    measurementId: 'G-Q9YBT6JH54',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAkergmO8SGVB2fyfH4g8OHvs4_gZs8zgQ',
    appId: '1:716831834046:android:c556bcb3971f3c982f83ef',
    messagingSenderId: '716831834046',
    projectId: 'app-segurity-64cb8',
    storageBucket: 'app-segurity-64cb8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyArRpkfiVeRBRayTgyWLQXB58xAEuNJ6Jo',
    appId: '1:716831834046:ios:1cbf1ed3137e5b242f83ef',
    messagingSenderId: '716831834046',
    projectId: 'app-segurity-64cb8',
    storageBucket: 'app-segurity-64cb8.firebasestorage.app',
    iosClientId: '716831834046-542r2ke4qo88g99c798cut56fk652fe4.apps.googleusercontent.com',
    iosBundleId: 'safety.app',
  );
}
